### ISSUE TITLE
Host models via Github Release

### ISSUE THREAD

**Issue by johnpaulbin** [Edresson/YourTTS#1]
Hi there! Awesome work on your code and paper!!!

I'm just concerned with where the models are currently hosted; they seem to be hosted via google drive, which isn't really a good solution since rate limiting occurs and restrictions are put into place. As an alternative, why not make a Github release and host the model binary on there for download? You get super fast speeds and last much longer

**Comment by WeberJulian** [comment]
Hey, thanks for your interest and for your suggestion!
The best checkpoint will be released as a coqui model when the PR is merged, so we'll update the colabs to point to their storage solution. The load on the other checkpoints should be low enough to keep on Google drive.
But we'll keep your solution in mind if we run into a quota issue!
