### ISSUE TITLE
finetune VC on my voice

### ISSUE THREAD

**Issue by odeliazavlianovSC** [Edresson/YourTTS#18]
I would like to finetune yourTTS voice conversion on my own voice, and compare it to the zero-shot model. Could you provide the finetuning procedure for VC?

**Comment by Edresson** [comment]
Hi, 
The procedure for VC finetuning is the same as the TTS finetuning. Check [this]( https://github.com/Edresson/YourTTS/issues/8#issuecomment-1033658910) for instructions.

**Comment by odeliazavlianovSC** [comment]
Thanks for your response.
It seems like the link leads to this issue, could you please change it to the correct address?

**Comment by Edresson** [comment]
Done 👍.
