### ISSUE TITLE
Can't reproduce Voice cloning with self trained model

### ISSUE THREAD

**Issue by WildAlejandro** [Edresson/YourTTS#24]
Zero-shot voice cloning works well with pretrained model. But i can't reproduce this result with self trained model. All voices sounds the same ofter cloning.

Model: https://drive.google.com/file/d/1HyF0Y7AlxBUGh_jTN6xEfwP6VE-nDCBh/view?usp=sharing
Config: https://github.com/WildAlejandro/TTS/blob/main/config.json

**Comment by Edresson** [comment]
How many speakers do you have in your dataset? If you don't have more than 100 speakers please try to train the model in multi-lingual mode to be able to use thousands of English speakers.

Recently, we created a recipe that makes everything easier. If you like you can try to fine-tune the model with this recipe.

The recipe replicates the first experiment proposed in the YourTTS paper. The recipe replicates the single language training using the VCTK dataset (it downloads, resamples, and extracts the speaker embeddings automatically :)). However, if you are interested in multilingual training, we have commented on parameters on the VitsArgs class instance that should be enabled for multilingual training: https://github.com/coqui-ai/TTS/blob/dev/recipes/vctk/yourtts/train_yourtts.py
