### ISSUE TITLE
Question regarding metadata and training (numbers)

### ISSUE THREAD

**Issue by michaellin99999** [Edresson/YourTTS#25]
In the metadata used to train the YourtTS model, if we have numbers, do we need to change it to text?

for example:
LJ Speech format:

audio_0001 |. I am 16 years old.    

Do i need to change 16 to sixteen?

**Comment by Edresson** [comment]
> In the metadata used to train the YourtTS model, if we have numbers, do we need to change it to text?
> 
> for example: LJ Speech format:
> 
> audio_0001 |. I am 16 years old.
> 
> Do i need to change 16 to sixteen?

YourTTS do not use any Phonemizer. eSpeak could deal with that but YourTTS do not uses it. Then yeah you need to expand numbers.
