### ISSUE TITLE
 Speaker Encoder train on new language

### ISSUE THREAD

**Issue by ikcla** [Edresson/YourTTS#27]
Hi,
Can you elaborate about the source of where you get  Speaker Encoder, and how do you train it with additional languages? How do you use model Wav2Vec which trained from fairseq?
on config_se.json "run_description": "resnet speaker encoder trained with commonvoice all languages dev and train, Voxceleb 1 dev and Voxceleb 2 dev". Which languages include in this CV? which version of CV in this training?
Thanks.

**Comment by WeberJulian** [comment]
Hey, the speaker encoder was only trained on English but in our tests it's worse if you train with multilingual data because it breaks cross lingual voice transfer. So go ahead and use that model for any language.

**Comment by ikcla** [comment]
@WeberJulian 
Thanks for your information. It helps to save me time. I have follow up questions:
in config_se.json, it is used 16000hz for wave forms. Is it working with 22050hz dataset? 
In your paper, you used pretrain LJS model which is default of 22050hz, but your model train with 16000hz. How was your experience with different frequency when you do knowledge transfer like restore weights params?
Thanks.

**Comment by WeberJulian** [comment]
We downsample everything to 16khz in our experiement, but you can use the speaker encoder for higher samplerate TTS, it's just gonna downsample the audio for embedding computation

**Comment by ikcla** [comment]
@WeberJulian
Thank you for insign information. I noticed I can use SE as 16K and it downsample data when embeddding computation, but it takes time. I tried to change SE config to 22050, and it went straight to compute without resampling. Do you think it will generate bad result for D vector file?
Can you also share if you trained your model with distributed GPUs in single node? I tried different versions including trainer.distribute as in the doc, but they all failed at 2 GPUs? exp CUDA_VISIBLE_DEVICES=0,1,2 python -m trainer.distribute --script train.py
thanks

**Comment by WeberJulian** [comment]
Yes it's gonna harm the embedding. We trained with a single GPU
