### ISSUE TITLE
Singing Voice Conversion?

### ISSUE THREAD

**Issue by dillfrescott** [Edresson/YourTTS#29]
Would it be possible to achieve singing voice conversion using one of the models?

**Comment by Edresson** [comment]
Hi, 

For singing  the voice conversion need to keep the pitch intact. The current YourTTS model was not designed for this task, so it will not works well. The current YourTTS model map the speech to the target speaker's pitch range (like most voice conversion models).

**Comment by dillfrescott** [comment]
If anyone happens to know any good SVC models please let me know! I've been searching for forever!

**Comment by chigkim** [comment]
@dillfrescott, have you got any answer?

**Comment by dillfrescott** [comment]
@chigkim https://github.com/fishaudio/fish-diffusion
