### ISSUE TITLE
Languages other than PT, FR, EN

### ISSUE THREAD

**Issue by start2018** [Edresson/YourTTS#3]
As YourTTS is multilingual TTS, I think that by training datasets, it seems that other languages might be available.
However, YourTTS's checkpoint structure seems distinctive.
Is there any training procedures that I can refer?

**Comment by WeberJulian** [comment]
Hi, yeah as soon our PR will be merged on https://github.com/coqui-ai/TTS. We'll provide recipes and we'll train a massively multilingual version of the model. One with phonemes, and one without so we can support more languages.

**Comment by ziyigit** [comment]
@Edresson @WeberJulian Thanks for your excellent project, I hope to use your method to train Korean Zero-Shot TTS in my research, but I can't find the training process of YourTTS on Coqui TTS, can you kindly give me some guidance? This will help me a lot, thank you in advance.

**Comment by start2018** [comment]
> @Edresson @WeberJulian Thanks for your excellent project, I hope to use your method to train Korean Zero-Shot TTS in my research, but I can't find the training process of YourTTS on Coqui TTS, can you kindly give me some guidance? This will help me a lot, thank you in advance.

I'm also thinking about using Korean in CoquiTTS's YourTTS. However, it doesn't seem like it will be available as model is quite limited. For now, how about using VC?

**Comment by ziyigit** [comment]
> > @Edresson @WeberJulian Thanks for your excellent project, I hope to use your method to train Korean Zero-Shot TTS in my research, but I can't find the training process of YourTTS on Coqui TTS, can you kindly give me some guidance? This will help me a lot, thank you in advance.
> 
> I'm also thinking about using Korean in CoquiTTS's YourTTS. However, it doesn't seem like it will be available as model is quite limited. For now, how about using VC?

Hi, Thanks for your reply.
I tried to use YourTTS Voice conversion also, but the speaker consistency is not very good. Is there any way to fine-tune to improve the speaker consistency?

**Comment by HoKim98** [comment]
> > > @Edresson @WeberJulian Thanks for your excellent project, I hope to use your method to train Korean Zero-Shot TTS in my research, but I can't find the training process of YourTTS on Coqui TTS, can you kindly give me some guidance? This will help me a lot, thank you in advance.
> > 
> > 
> > I'm also thinking about using Korean in CoquiTTS's YourTTS. However, it doesn't seem like it will be available as model is quite limited. For now, how about using VC?
> 
> Hi, Thanks for your reply. I tried to use YourTTS Voice conversion also, but the speaker consistency is not very good. Is there any way to fine-tune to improve the speaker consistency?

Same idea. As a native CJK speaker that is far from Indo-European languages, I think the quality is quite poor to hear when it comes to a generated CV audio.

**Comment by annaklyueva** [comment]
@WeberJulian Hi!

You mentioned that there will be a recipe to train a model on other languages using massively multilingual version of the model trained by you. Could you please share the link to the recipe if it is available or maybe explain how to train the existing model on another language?

**Comment by Edresson** [comment]
> @WeberJulian Hi!
> 
> You mentioned that there will be a recipe to train a model on other languages using massively multilingual version of the model trained by you. Could you please share the link to the recipe if it is available or maybe explain how to train the existing model on another language?

Recently, we created a recipe that makes everything easier. If you like you can try to fine-tune the model with this recipe.

The recipe replicates the first experiment proposed in the YourTTS paper. The recipe replicates the single language training using the VCTK dataset (it downloads, resamples, and extracts the speaker embeddings automatically :)). However, if you are interested in multilingual training, we have commented on parameters on the VitsArgs class instance that should be enabled for multilingual training: https://github.com/coqui-ai/TTS/blob/dev/recipes/vctk/yourtts/train_yourtts.py

**Comment by anusha-potnuru** [comment]
> Hi, yeah as soon our PR will be merged on https://github.com/coqui-ai/TTS. We'll provide recipes and we'll train a massively multilingual version of the model. One with phonemes, and one without so we can support more languages.

Have any pretrained models been trained on phonemes instead of characters?
