### ISSUE TITLE
Installation Issue "numpy.ndarray size changed"

### ISSUE THREAD

**Issue by MartinMashalov** [Edresson/YourTTS#30]
Hello, 

I am installing TTS for Zero-Shot Voice Cloning purposes but I am encountering the issue: "numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". I have downloaded both TTS==0.7.0 and TTS==0.8.0 and the error arises in both cases. Could you please offer some assistance in overcoming this error? 

Thank you. 

Martin

**Comment by Edresson** [comment]
Hi, could you try it using the latest Coqui TTS version? 

Please do not uses the notebook and try to use the command described here: https://github.com/Edresson/YourTTS#voice-conversion
