### ISSUE TITLE
Zeroshot TTS notebook no longer working

### ISSUE THREAD

**Issue by vince62s** [Edresson/YourTTS#4]
Hi @Edresson @WeberJulian 

the demo notebook is no longer working with the current TTS master repo.

I'm having hard time to execute things.

Do you intend to adjust ?
thanks

**Comment by vince62s** [comment]
I managed to make it work with some adjustments.

**Comment by jerrymatjila** [comment]
@vince62s If you don't mind, kindly share details of adjustments to make it work.

**Comment by vince62s** [comment]
replace this:
model = setup_model(C)
model.language_manager.set_language_ids_from_file(TTS_LANGUAGES)

by this:
language_manager = LanguageManager(TTS_LANGUAGES)
speaker_manager = SpeakerManager()

model = setup_model(C, language_manager=language_manager, speaker_manager=speaker_manager)

**Comment by farazBhatti** [comment]
@vince62s 'LanguageManager' is not defined
