### ISSUE TITLE
Training yourtts with 48k sampling rate audio

### ISSUE THREAD

**Issue by gashishoo7** [Edresson/YourTTS#45]
Hi, I want to train yourTTS model using 48khz sampling rate audio. It would be great help if you could guide me what are the changes are needed. Do I have to change model layers?

**Comment by Edresson** [comment]
It does not require any model architecture changes. You can use the [YourTTS recipe](https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/recipes/vctk/yourtts/train_yourtts.py) by changing the [sampling rate](https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/recipes/vctk/yourtts/train_yourtts.py#L43).

**Comment by gashishoo7** [comment]
Thanks a lot for your suggestion. It worked. Sorry for late reply as my training was going on. But I am facing issues with voice cloning and getting some noise in the output audio. In my dataset I have 30 speakers data. How to get good quality in voice cloning? Can you suggest something on that?

**Comment by gashishoo7** [comment]
And when I try to run training on multiple gpu it giving the following error. On single gpu it works fine.

/TTS/TTS/tts/models/vits.py", line 262, in __getitem__
    item = self.samples[idx]
TypeError: list indices must be integers or slices, not list
