### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by e0xextazy** [Edresson/YourTTS#6]
Thanks for the great job! You have checkpoints on google drive and it's not clear what they mean. Could you describe these checkpoints or put them in order on the drive?

**Comment by Edresson** [comment]
Hi, 
You can check the checkpoint link for each experiment [here](https://github.com/Edresson/YourTTS#checkpoints) 
For all experiments, the best checkpoint is "best_model_latest.pth.tar".

**Comment by e0xextazy** [comment]
use 4 exp, have a error: 
`FileNotFoundError: [Errno 2] No such file or directory: '/app/../speaker_embeddings/new-SE/VCTK-LibriTTS+TTS-PT+MAILABS-FR/speakers.json'`
