### ISSUE TITLE
Select Speakers for Zero Shot TTS

### ISSUE THREAD

**Issue by dipanjannC** [Edresson/YourTTS#9]
Hi , 

Firstly great work on the project with time trying to understand the repo with more clarity. Wanted to know  how can I select different speakers for different sections of text .

Thanks in advance.

**Comment by Edresson** [comment]
Hi, I don't know if a fully understand your question. Do you want to know the test speakers set for each dataset? If it is your question I added the list of test speakers for each dataset  [here](https://github.com/Edresson/YourTTS/blob/main/README.md#test-speakers).

**Comment by dipanjannC** [comment]
Hi Edresson , 

Actually , I'm referencing your YourTTS-zeroshot-TTS-demo notebook . I want to generate two types of speakers from the speaker's list for diagloue generation . Can you help me how to tweak the config.json to do that ? Or is there something else I need to do?

**Comment by Edresson** [comment]
Hi, the [YourTTS-zeroshot-TTS Colab notebook](https://colab.research.google.com/drive/1ftI0x16iqKgiQFgTjTDgRpOM1wC1U-yS?usp=sharing) receives audio as a reference and generates the voice in the speaker reference voice.  You just need to upload a reference for every speaker that you want and generate speech in their voice.

**Comment by dipanjannC** [comment]
Yes, Thanks .  we can store it in different variables . 

Bdw, how can we expand the language model ? suppose I want to train my model to generate hindi voices. 

And is there any similarity metric to find the similarity between , real and the generated audio.
